### ISSUE TITLE
Accept type definitions?

### ISSUE THREAD

**Issue by nicojs** [cnlon/promisified-fs#1]
This repo is just what I'm looking for. It uses native es promises (in contrary to mz/fs for example). However it lacks typescript type definitions. Would you be willing to accept a PR that adds them?

**Comment by cnlon** [comment]
Welcome

**Comment by nicojs** [comment]
Sorry. We also needed a promisified implementation of child_process, so I've decided to backport `require('util').promisify` instead. Thanks for replying though 👍
